### ISSUE TITLE
Code issues with Pokémon Omega Ruby (EU)

### ISSUE THREAD

**Issue by wrathsoffire76** [BernardoGiordano/Sharkive#1]
## Issue template

* [] Issue with Sharkive
* [x] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**: 
* **Encountered behavior**: 

### Fill this for problems with codes in the database

* **Title ID**: 0011C400
* **Product code**: CTR-P-ECRA

### Not working codes

* Every single one came up red and the Route 116 Mew didn't work for me either

**Comment by BernardoGiordano** [comment]
Closing because this needs to be re-checked due to latest Luma changes.
