### ISSUE TITLE
Code Issues with Pokemon Ultra Sun (US)

### ISSUE THREAD

**Issue by JustPlayJared** [BernardoGiordano/Sharkive#11]
## Issue template

* [X] Issue with Sharkive
* [X] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behavior**: Display "Codes available on DB."
* **Encountered behavior**: "Codes not available in DB. Would you mind to contribute? :)"

- Also, the app was open for a considerable amount of time (the length of writing all these issues up), so I'm convinced it's not just still loading from the database.

### Fill this for problems with codes in the database

* **Title ID**: 001B5000
* **Product code**: CTR-P-A2AA
* **Game version**: 1.0/1.1

### Red codes

(Listed in order of appearance on the code list)
- Unlock Mega Evolution v1.0
- Can use mega evolution multiple times i
- Always critical hit v1.0
- Language change v1.0
- EXP multiplier *X v1.0
- Hold SELECT to view IVs & Hold START to
- Poke Finder get point multiplier v1.0
- HP Not Decrease v1.0
- PP Not Decrease v1.0
- Fix stat of a pokemon in battle v1.0
- Can throw Pokeball at Trial v1.0
- Can use Z-moves multiple times v1.0
- Camera zoom out (SELECT+L)Enable, (SELEC
- *No Encounter, Hold START Instant Encoun
- No Forced Trainer Battles v1.0
- QR Scan Point 100 v1.0
- Walk & Run Speed Multiplier v1.0
- BP9999 v1.0
- Max Money v1.0
- 100%Catch v1.0
- Catch Trainer’s Pokemon v1.0
- Unlock All PokePuffs
- Wild Pokemon Modifier v1.0
- Random Wild Pokemon Encounter v1.0
- Ultra Wormhole Color & Rarity v1.0

### Codes that crash Luma (only when using update 1.1)

- (Hold START and Open OPTIONS menu) Acces
- Camera zoom out (SELECT+L)Enable, (SELEC

[Pokemon Ultra Sun Crash Dumps.zip](https://github.com/BernardoGiordano/Sharkive/files/1629490/Pokemon.Ultra.Sun.Crash.Dumps.zip)

**Comment by AnalogMan151** [comment]
It looks like there's more codes in this file then Luma3DS can show. It only goes to (SELECT + UP)All ITEMS x950 v1.1 which is the first of the v1.1 cheats, the rest of the v1.1 cheats are after this. All other cheats are for v1.0 but their names are so long they get cut off. Unless we separate the cheat files by game version, some games like Pokémon that tend to have a lot of cheats for them may require manual editing of the cheat.txt file after downloading.

**Comment by BernardoGiordano** [comment]
Closing because this needs to be re-checked due to latest Luma changes.
