### ISSUE TITLE
Code Issue with Pokémon UltraMoon (US)

### ISSUE THREAD

**Issue by Maximumride1126** [BernardoGiordano/Sharkive#13]
## Issue template

* [] Issue with Sharkive
* [x] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **001B5100**:
* **CTR-P-A2BA**:
* **v 1.1**:

### Not working codes

Codes in red:
Can use mega evolution multiple times
*Hold SELECT to view IVs & Hold START to
*camera zoom out(SELECT+L) Enable,
*NO Encounter, Hold START Instant encounter
Unlock Mega Evolution v1.1
Language change v1.1
Max Money v1.1
BP9999 v1.1
QR Scan Point 100 v1.1
No forced trainer battles v1.1
Can use Z-moves multiple times v1.1
Can throw Pokeball at Trial v1.1
Poke Finder get point multiplier v1.1
View IVs & EVs on Pokemon Status Screen
Can use mega evolution multiple times
PP Not Decrease v1.1
HP Not Decrease v1.1
Always critical hit v1.1
Mega Evolve Without Holding the Stones

Codes that don't work:
Can learn the all moves in Move Reminder
100%Catch(Gateshork2NTR only)
*(SELECT + UP)ALL ITEMS x950 v1.1
*(SELECT + UP)ALL TMs & HMs v1.1
*(SELECT + UP)ALL MEDICINE x950 v1.1
*(SELECT + UP)ALL BERRIES x950 v1.1
*(SELECT + UP)ALL Z-Crystal v1.1
*(SELECT + UP)ALL Rotom Power x950 v1.1
*(SELECT + UP)ALL Clothes(male) v1.1
*(SELECT + UP)ALL Clothes(female) v1.1

Codes that crash the game:
100%Catch(Gateshork2NTR only) (Only crashes when you try to use charizard fly, doesn't crash if you go to isle abeens)

Could not test:
[Mega evolution of party pokemon does not cancel after load v1.1]
[Mega evolution does not cancel after battle v1.1]

**Comment by BernardoGiordano** [comment]
Closing because this needs to be re-checked due to latest Luma changes.
