### ISSUE TITLE
Code issues with Ice Station Z (EU)

### ISSUE THREAD

**Issue by wrathsoffire76** [BernardoGiordano/Sharkive#15]
## Issue template

* [] Issue with Sharkive
* [x] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**: 00199700
* **Product code**: CTR-N-KZSP
* **Game version**: 1.1

### Not working codes

* Infinite Health
* No Hungry
* Infinite Battery
* No Thirsty
* Clothes Modifier
* Display Player Names

All of these crash Rosalina

[dumps.zip](https://github.com/BernardoGiordano/Sharkive/files/1632421/dumps.zip)

**Comment by BernardoGiordano** [comment]
Closing because this needs to be re-checked due to latest Luma changes.
