### ISSUE TITLE
Code Issues with Mario Kart 7 (EU)

### ISSUE THREAD

**Issue by wrathsoffire76** [BernardoGiordano/Sharkive#16]
## Issue template

* [] Issue with Sharkive
* [x] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**: 00030700
* **Product code**: CTR-P-AMKP
* **Game version**: 1.1

### Not working codes

* Every code (Probably 1.0 codes)

**Comment by BernardoGiordano** [comment]
Closing because this needs to be re-checked due to latest Luma changes.
