### ISSUE TITLE
Code Issues with Pokémon Moon (EU)

### ISSUE THREAD

**Issue by wrathsoffire76** [BernardoGiordano/Sharkive#17]
## Issue template

* [] Issue with Sharkive
* [X] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**:
* **Product code**:
* **Game version**:

### Not working codes

* Max Money
* 100% catch
* Catch Trainers Pokémon
* No Forced Trainer Battles
* Egg Instant Hatch
* No Encounter
* Wild Pokémon Modifier
* Camera Zoom
* View IVs/EVs on Pokémon
* Can use Z-Moves many times
* 250,000 FC
* 500,000 Total earned FC 
* 99 of all Poké Beans
* Enable view of enemy Pokémon HP
* Always critical hit
* Can throw Pokéball at trial
* Unlimited HP
* Island scan ready
* Max Money
* 9999 BP

**Comment by lorilith** [comment]
missing the "Fill this for problems with codes in the database" section. patches change offsets for cheats, version information and title id is needed

**Comment by JourneyOver** [comment]
One thing to note @lorilith is the date that this issue was made, things have since changed and some of these code may now work, ontop of that some of the codes have since been removed as well.

Literally every issue other than #20 and #21 will need to be relooked at and have their issues updated to reflect recent changes to the luma build.

**Comment by lorilith** [comment]
well...luma hasnt changed since Dec, and this entry was made in Jan, so we are still on the same version as when the issue was made. Also, point is still valid that codes are version specific many times and not providing the requisite information makes the issue moot.

**Comment by BernardoGiordano** [comment]
Not true. The issue was made with a different codebase for the PR, and the Gateshark cheat code reader was buggy at the moment, since it didn't recognize any of the codes that we're instead valid syntax-wise

**Comment by BernardoGiordano** [comment]
Closing because this needs to be re-checked due to latest Luma changes.
