### ISSUE TITLE
Code Issues with New Super Mario Bros. 2 (USA)

### ISSUE THREAD

**Issue by JourneyOver** [BernardoGiordano/Sharkive#18]
## Issue template

* [] Issue with Sharkive
* [x] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**: 0007AE00
* **Product code**: CTR-P-ABEE
* **Game version**: 1.0 (normal edition with DLC)

### Not working codes

* [Freeze Timer, Doesn't show in interface]
* [500 star coins]
* [Regular Mario]
* [Super Mario]
* [Fire Mario]
* [Mini Mario]
* [Gold Mario]
* [Gold Tanooki Mario]
* [L+R add 100000 coins in Stage]
* [Reset Amount of Coins in Stage]
* [Infinite Coins]
* [Invincible]

### Red codes

* [Invincible L+RIGHT BrowserCastle]
* [Small Mario L and LEFT]
* [Big Mario L and DOWN]
* [Gold Mario L and UP]
* [Invincibe Mario R and RIGHT]
* [Raccoon Mario R and LEFT]
* [Mini Mario R and DOWN]
* [Fire Mario R and UP]
* [Small Mario L+LEFT, Browser Castle]
* [Big Mario L+DOWN, Browser Castle]
* [Gold Mario L+UP, Browser Castle]
* [Raccoon Mario R+LEFT, Browser Castle]
* [Mini Mario R+DOWN, Browser Castle]
* [Fire Mario R+UP, Browser Castle]
* [(static) Max Inf lives *v1.0]

### Notes

* [Always have 99 ,Coins Doesn't show in interface] (This cheat works but it seems you have to turn it off and on each time you want it to actually give you a 1-up from the next coin)

**Comment by BernardoGiordano** [comment]
Closing because this needs to be re-checked due to latest Luma changes.
