### ISSUE TITLE
Code issues with 3D Classics Kirby's Adventure (EU)

### ISSUE THREAD

**Issue by wrathsoffire76** [BernardoGiordano/Sharkive#2]
## Issue template

* [] Issue with Sharkive
* [x] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**: 00055000
* **Product code**: CTR-N-SAFP

### Not working codes

* Max lives after losing

**Comment by BernardoGiordano** [comment]
Closing because this needs to be re-checked due to latest Luma changes.
