### ISSUE TITLE
Both pkm UsUm crashes

### ISSUE THREAD

**Issue by JamSky170** [BernardoGiordano/Sharkive#20]
## Issue template

* [?] Issue with Sharkive
* [] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**: Not sure if its sharkive or the boot.firm but game crashes when you try to load your save file

### Fill this for problems with codes in the database

* **Title ID**:
* **Product code**:
* **Game version**:

### Not working codes

* code 1
* code 2
* ...

**Comment by BernardoGiordano** [comment]
Not enought detailed, closing
