### ISSUE TITLE
New "New super mario bros 2" codes

### ISSUE THREAD

**Issue by SpongebobPlace** [BernardoGiordano/Sharkive#26]
1. Invincibility (different then the broken one that was removed)
D3000000 00000000
001F6F78 E3500001
D2000000 00000000

2. Always shoot normal fireballs
D3000000 00000000
0026C4BC E1A00000
00268C54 EA00000A
00268D50 E1A00000
002676B8 EA000006
D2000000 00000000

SOURCE: https://gamehacking.org/game/115234

**Comment by JourneyOver** [comment]
This is not how to do a pull request..

Closing this.
