### ISSUE TITLE
Code issues with Animal Crossing: New Leaf (EU)

### ISSUE THREAD

**Issue by wrathsoffire76** [BernardoGiordano/Sharkive#3]
## Issue template

* [] Issue with Sharkive
* [X] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**: 00086400
* **Product code**: CTR-P-EGDP

### Not working codes

* Text to Item Part 1
* Text to Item Part 2
* Text to Item Part 3
* Coordinates Modifer
* Teleport

**Comment by BernardoGiordano** [comment]
Closing because this needs to be re-checked due to latest Luma changes.

**Comment by JourneyOver** [comment]
Will look into them the at some point today.
