### ISSUE TITLE
Maplestory 3DS: The Girl of Destiny

### ISSUE THREAD

**Issue by aznchronos** [BernardoGiordano/Sharkive#38]
## Issue template

* [Game Codes for Maplestory 3DS: The Girl of Destiny not functioning] Issue with Sharkive
* [All of the Codes] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**: 00111600
* **Product code**: CTR-P-BMPE
* **Game version**: 1.0

### Not working codes

* Infinite HP
* Infinite MP
* EXP Max
* Money Max

**Comment by JourneyOver** [comment]
So I base my tests on non-modded variants as that's how it should be, anyways only one code came back working out of the 4 that you mentioned broken and that is "max money". So I removed the 3 others and left max money.
