### ISSUE TITLE
Code Issues with Azure Striker Gunvolt (US)

### ISSUE THREAD

**Issue by JustPlayJared** [BernardoGiordano/Sharkive#4]
## Issue template

* [] Issue with Sharkive
* [x] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**: 0014C800
* **Product code**: CTR-N-JV7E
* **Game version**: 1.4

### Not working codes

* Inf HP: 
* Infinite Health, Game v1.0
* Infinite Health, Game v1.2
* Infinite Health

**Comment by BernardoGiordano** [comment]
Closing because this needs to be re-checked due to latest Luma changes.
