### ISSUE TITLE
Codes don't download

### ISSUE THREAD

**Issue by Seddigirl** [BernardoGiordano/Sharkive#41]
* [x] Issue with Sharkive
* [ ] Issue with one or more codes in the database

latest git build used

* **Expected behaviour**: Codes are downloaded from the database
* **Encountered behavior**: Codes don't download from the database: https://gfycat.com/SpeedyRectangularHatchetfish

**Comment by BernardoGiordano** [comment]
That's not a problem with Sharkive, but with 3ds-curl.

**Comment by Seddigirl** [comment]
i'm using `3ds-curl 7.58.0-1` from dkp-libs

**Comment by BernardoGiordano** [comment]
That's the 3ds-curl which is buggy at the moment

**Comment by Xeddius** [comment]
Make sure to use the version of Sharkive from Discord. It's the only legit cia that works.

**Comment by magarto** [comment]
When I open Sharkive, only a few games are found. Everyone only shows "Codes not available on SD" and "Codes not available on DB". I meant that no cheats are found on any game and only a few number of games are showed on Sharkive
