### ISSUE TITLE
Pokemon Super Mystery Dungeon codes not working

### ISSUE THREAD

**Issue by eifirelight** [BernardoGiordano/Sharkive#47]
Pokemon Super Mystery Dungeon (USA)
00174600
North America

None of the codes I tried work properly if they do anything at all. The only one that did anything was the infinite pp code activated in a dungeon, but it changed three of my and my partner's moves to Rage, instead of doing anything with PP.

**Comment by JourneyOver** [comment]
Will take a look in the next day or so, gotta download the game myself and get a decent amount of length into the game to test some of the codes out.

---

Making a note to myself (fort42 web archived page https://web.archive.org/web/20171026030753/http://www.fort42.com/gateshark/game1782/) so I can check for special stuff.

**Comment by JourneyOver** [comment]
So I tested the codes out and they are made for only version 1.0, there are some that seem to be kinda glitchy (don't fully work) on the update, like for example the `Max EXP for Slots 1 through 3` code semi-works on the update as in it'll glitch out your HP and make it 500 for some reason but it won't do anything else. 

So I dunno how I completely feel about those codes right now, but I'm going to leave them in either way as they do work for at least version 1.0 of the game.
