### ISSUE TITLE
Code Issues with Azure Striker Gunvolt 2 (US)

### ISSUE THREAD

**Issue by JustPlayJared** [BernardoGiordano/Sharkive#5]
## Issue template

* [] Issue with Sharkive
* [X] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**: 00196A00
* **Product code**: CTR-N-KGBE
* **Game version**: 1.2

### Not working codes

* Infinite Health (Gunvolt + Copen)

**Comment by BernardoGiordano** [comment]
Closing because this needs to be re-checked due to latest Luma changes.
