### ISSUE TITLE
Monster Hunter Generations code issue

### ISSUE THREAD

**Issue by unskilledmagician** [BernardoGiordano/Sharkive#50]
## Issue template

* [] Issue with Sharkive
* [x] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**: 0004000000187000
* **Product code**: CTR-P-BXXE
* **Game version**: 16 (0.1.0

### Not working codes

* *[(SELECT+START)all talisman slot3 v1.0
* [armor skills v1.0]
* [armor skills extension slot +24 v1.0] 
* [prowler support gauge max v1.0]

**Comment by JourneyOver** [comment]
Please fill these in 
```
Title ID:

Product code:

Game version:
```

**Comment by unskilledmagician** [comment]
i thought i did, sorry i will fix it tomorrow

**Comment by JourneyOver** [comment]
You seemed to have fixed it already, at first they wasn't there xD

I'll be looking into this and your other issue sometime tomorrow.

**Comment by unskilledmagician** [comment]
ok thanks
