### ISSUE TITLE
devil summoner soul hackers usa cheat not working

### ISSUE THREAD

**Issue by mileyrock** [BernardoGiordano/Sharkive#55]
### Fill this for problems with codes in the database

* **00040000000C5600**:
* **CTR-P-AHQE**:
* **v0.0.0**:

### Not working codes

* hero max exp
* code 2
* ...

**Comment by mileyrock** [comment]
for some reason it gives me infinite hp the max exp for nimissa works though

**Comment by JourneyOver** [comment]
So do all codes not work? or just the hero max exp?

**Comment by mileyrock** [comment]
just the exp

**Comment by JourneyOver** [comment]
Alright well this has already been solved then ^^
