### ISSUE TITLE
0004000000074600 Codes not working

### ISSUE THREAD

**Issue by Naifus** [BernardoGiordano/Sharkive#57]
## Issue template
* [ ] Issue with Sharkive
* [x] Issue with one or more codes in the database

### Fill this for problems with codes in the database
The game is patched with the [English patch](https://gbatemp.net/threads/translation-dragon-quest-monsters-terrys-wonderland-3d.431204/)
* **Title ID**: 0004000000074600
* **Product code**: CTR-P-ATWJ 
* **Game version**: 0 (0.0.0) and the update: 1024 (1.0.0)

### Not working codes
The only working code is:  **All items x99**

### Codes made by me
I have created many codes that works perfectly with this game version (at least for me).

**[999 999 Gold]**
`005864A4 000F423F`

**[100% Scout]**
`005582FC 000003E8`

**[99 Minimedals]**
`005865D0 00000063`

**[White Egg x1]**
`005865D4 00000001`

**[Silver Egg x1]**
`005865D5 00000001`

**[Gold Egg x1]**
`005865D6 00000001`

**[Rainbow Egg x1]**
`005865D7 00000001`

Cheers and thank you for your time!

**Comment by JourneyOver** [comment]
Since I couldn't find a copy anywhere for a non english patched version of this game that wasn't a dead link already I'll just take your word that the codes don't work and remove them..

Thanks for the extra codes though!
