### ISSUE TITLE
Code Issues with Animal Crossing: New Leaf (US)

### ISSUE THREAD

**Issue by JustPlayJared** [BernardoGiordano/Sharkive#6]
## Issue template

* [] Issue with Sharkive
* [X] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**: 00086300
* **Product code**: CTR-P-EGDE
* **Game version**: 1.5

### Not working codes

* *L+Right & L+Left To cycle fruit
* Player 1 Appearance Modifer
* Unlock Nook’s Emporium

**Comment by BernardoGiordano** [comment]
Closing because this needs to be re-checked due to latest Luma changes.
