### ISSUE TITLE
MH3U codes not working

### ISSUE THREAD

**Issue by Rdpruitt** [BernardoGiordano/Sharkive#63]
## Issue template

* [] Issue with Sharkive
* [☑️] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**:000AE400
* **Product code**:CTR-P-AMHE
* **Game version**:

### Not working codes

[Inf hp]
[Inf stamina]
*[LEVITATE (L+R+B)]
*[ALMIGHTY GRAVITY! (B+A)]
*[FAST MOVEMENT (PRESS R) (QUEST ONLY!)]
*[FAST MOVEMENT WITHOUT WEAPON (PRESS R)
*[REPEAT CURRENT MOVEMENT (B+Y) (QUEST ONLY)]
[INFINITE HP]
[INFINITE STAMINA]
[INFINITE OXYGEN]
[UNLIMITED PSYCHOSERUM EFFECT]
[NO DEATH COUNTS WHEN FAINTING (ZENNY R
[HAVE MAP ON LAST ITEM SLOT (QUEST ONLY)]
[HAVE TORCH ON 2nd LAST ITEM SLOT (QUEST ONLY)]
[HAVE PAW PASS TICKET ON 3rd LAST ITEM SLOT (QUEST ONLY)]
[QUEST ITEM POUCH x99]
[VILLAGE ITEM POUCH X99]

**Comment by JourneyOver** [comment]
> Nearly all of them

This doesn't tell me jack squat...You need to put down which ones are not working.. not just say "nearly" all of them..because that is vague as hell.

**Comment by Rdpruitt** [comment]
And every single PRESS KICK ICON ones don't work.
And will you fix all the cheats I posted above or just remove them? Because personally I really want the LEVITATE one to work. That was the main reason I downloaded sharkive on my 3ds.

**Comment by BernardoGiordano** [comment]
Just to make it clear: we make the software and manage the cheats, but we **don't** make the cheats

**Comment by Rdpruitt** [comment]
Ok :(

**Comment by JourneyOver** [comment]
@Rdpruitt the cheats "may" work it's just that they may be AR instead of gateshark, 99% of the codes in the DB came from my own repo that is a mix between AR and gateshark codes and well luma's cheat menu doesn't support AR at all. We are slowly weeding out the AR codes while also taking out just general broken codes but it all takes time to do.

If you want you can always download CTRPF and try the cheats with it (you'll have to manually download and move things to the correct locations though as sharkive doesn't support CTRPF), it could end up working.

As for here, I'll remove the cheats that you have now wrote down so thanks.

**Comment by Rdpruitt** [comment]
How would I find this cheat to download it into ctrpf, because trust me I've looked EVERYWHERE for these exact codes and can't find them , except in a .txt file. Can I use a txt for ctrpf?

**Comment by JourneyOver** [comment]
Yes, you can use .txt files for CTRPF.. https://gbatemp.net/threads/ctrpluginframework-blank-plugin-now-with-action-replay.487729/ Read the Action Replay section.

**Comment by Rdpruitt** [comment]
Awesome, but is the Monster Hunter 3 Ultimate .txt file in the following link a gateshark? Just wondering if it will work as it is in ctrpf. 
https://gbatemp.net/threads/database-ctrpf-ar-cheat-codes.493220/page-9#post-7798037

**Comment by JourneyOver** [comment]
It's literally the same file as the one in the DB, except for the notes/folder stuff being ripped out on the txt file in the DB as luma's cheat menu doesn't support notes/folders.

**Comment by Rdpruitt** [comment]
So if it doesn't work in Luma, would it work in ctrpf?

**Comment by JourneyOver** [comment]
I'm not saying it will or it won't but it might, All I can say is just to test it out.
