### ISSUE TITLE
ideas....not to much English speaker.

### ISSUE THREAD

**Issue by jvhellraiser** [BernardoGiordano/Sharkive#65]
Unless Luma gets better on reading cheats and leaving them on the memory i will recommend for the cheats to be download to the cheat folder on the SD card, like this i can use Actionreplay.plg to leave the codes in the memory using NTR loader. if the cheats go to a DB file Actionreplay.plg can't read the file and cheats wont appear but in the cheat folder using .txt files it can and it will work,doing so will leave the codes in the memory and they will stay enable until you closed the game.

**Comment by JourneyOver** [comment]
Ugh?? We do not support CTRPF/ActionReplay any. We support luma's cheat menu.

As for codes staying enabled until you close the game, if the cheat is made to do so then it already does this.
