### ISSUE TITLE
Code issues with Pokémon Omega Ruby (EU)

### ISSUE THREAD

**Issue by thorsb** [BernardoGiordano/Sharkive#68]
## Issue template

* [ ] Issue with Sharkive
* [x] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Title ID**:0011C400
* **Product code**:CTR-P-ECRA
* **Game version**:1.4

### Not working codes

* [DexNav Pokemon Generator]
00000000 00000000

### Notes

[Max All AP 3rd PKMN (Press R) v1.4] is the last code visible in the luma cheat list, so I can't test any codes from line 920+

**Comment by JourneyOver** [comment]
> [Max All AP 3rd PKMN (Press R) v1.4] is the last code visible in the luma cheat list, so I can't test any codes from line 920+

yea sadly luma's cheat menu has a limit on how many codes it can show, so for games with a big list of cheats (like some of the pokemon games) you'll more than likely need to go in and parse out the codes that you don't want to use and only keep the codes you do want to use.

**Comment by thorsb** [comment]
I manage to test the rest of the codes by deleting the ones i'd already tested, and none of the others showed up as red.

**Comment by JourneyOver** [comment]
so the dexnav pokemon generator code is the only code that didn't work?

**Comment by thorsb** [comment]
Yes, while i didn't test the functionality of the codes, they all activated and the game seemed fine (didn't crash)

**Comment by JourneyOver** [comment]
Alright, well I'll at least remove that code.
