### ISSUE TITLE
Code Issues with Kirby: Triple Deluxe (US)

### ISSUE THREAD

**Issue by JustPlayJared** [BernardoGiordano/Sharkive#7]
## Issue template

* [] Issue with Sharkive
* [X] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**: 0010BF00
* **Product code**: CTR-P-BALE
* **Game version**: 1.0

### Not working codes

* Max Lives after losing
* 99 Stars
* 99 Lives

**Comment by BernardoGiordano** [comment]
Closing because this needs to be re-checked due to latest Luma changes.
