### ISSUE TITLE
[CODES] New Super Mario Bros. 2: Gold Edition (USA)

### ISSUE THREAD

**Issue by yonaikerlol** [BernardoGiordano/Sharkive#70]
## Issue template

* [] Issue with Sharkive
* [x] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**: 0004000000137E00
* **Product code**: CTR-P-BMAE
* **Game version**: 0 (0.0.0)

### Not working codes

* [Max Infinite Lives]
D3000000 00000000
004106EC E5801004
* [Small Mario L and LEFT]
DD000000 00000220
D3000000 00000000
605E7210 00000000
B05E7210 00000000
40000364 14000000
B0000364 00000000
20000015 00000000
D2000000 00000000
* [Big Mario L and DOWN]
DD000000 00000280
D3000000 00000000
605E7210 00000000
B05E7210 00000000
40000364 14000000
B0000364 00000000
20000015 00000001
D2000000 00000000
* [Gold Mario L and UP]
DD000000 00000240
D3000000 00000000
605E7210 00000000
B05E7210 00000000
40000364 14000000
B0000364 00000000
20000015 00000006
D2000000 00000000
* [Invincibe Mario R and RIGHT]
DD000000 00000110
D3000000 00000000
605E7210 00000000
B05E7210 00000000
40000364 14000000
B0000364 00000000
20000015 00000007
D2000000 00000000
* [Raccoon Mario R and LEFT]
DD000000 00000120
D3000000 00000000
605E7210 00000000
B05E7210 00000000
40000364 14000000
B0000364 00000000
20000015 00000004
D2000000 00000000
* [Mini Mario R and DOWN]
DD000000 00000180
D3000000 00000000
605E7210 00000000
B05E7210 00000000
40000364 14000000
B0000364 00000000
20000015 00000003
D2000000 00000000
* [Fire Mario R and UP]
DD000000 00000140
D3000000 00000000
605E7210 00000000
B05E7210 00000000
40000364 14000000
B0000364 00000000
20000015 00000002
D2000000 00000000
* [L+R add 100000 coins in Stage]
DD000000 00000300
D3000000 00000000
605E7210 00000000
B05E7210 00000000
000000B0 000186A0
D2000000 00000000
* [Always Invincible]
605E7210 00000000
B05E7210 00000000
000017AC 0001869F
D2000000 00000000
* [Always have 99 coins]
D3000000 14000000
0015E468 00000063
* [Always Invincible]
605E7210 00000000
B05E7210 00000000
000017AC 0001869F
D2000000 00000000
* [Always Blockhead]
D3000000 10000000
6402FE78 00000000
B402FE78 00000000
000048C8 000003E7
D2000000 00000000

OLD3DS (USA)
Luma3DS v9.1
Boot9Strap v1.3
Sharkive 1.0.0

**Comment by JourneyOver** [comment]
`[Max Infinite Lives]` works but you have to kill mario before the life counter actually shows this, for the other codes I have removed them as I have confirmed they are broken.

**Comment by Smoker1** [comment]
Not working here as well. The Inf Time works, but none of the Commands work either. Use the Action Replay Plugin and it works perfectly. But would rather use Rosalina Cheat System. Needs improvements. As well as Searching for new Cheats or creating new Cheats.
