### ISSUE TITLE
[CODES] Super Mario 3D LAND (USA)

### ISSUE THREAD

**Issue by yonaikerlol** [BernardoGiordano/Sharkive#71]
## Issue template

* [] Issue with Sharkive
* [x] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**: 0004000000054000
* **Product code**: CTR-P-AREE
* **Game version**: 48 (0.3.0)

### Not working codes

* [Make Timer countdown from 999]
D3000000 14000000
02197A40 000055DA
* [Lower Slot have Fire Flower]
D3000000 14000000
22197A30 00000002
* [Lower Slot have Mushroom]
D3000000 14000000
22197A30 00000001
* [Lower Slot Item (Select + Right or Left or Up or Down or R or L)]
D3000000 14000000
DD000000 00000014
22197A30 00000001
D0000000 00000000
DD000000 00000024
22197A30 00000002
D0000000 00000000
DD000000 00000044
22197A30 00000003
D0000000 00000000
DD000000 00000084
22197A30 00000004
D0000000 00000000
DD000000 00000104
22197A30 00000005
D0000000 00000000
DD000000 00000204
22197A30 00000006
D0000000 00000000
* [Lower Slot have Super Leaf]
D3000000 14000000
22197A30 00000003
* [Lower Slot have Boomerang]
D3000000 14000000
22197A30 00000005
* [Lower Slot have Tanooki/Statue Leaf]
D3000000 14000000
22197A30 00000004
* [Lower Slot have P-Wings]
D3000000 14000000
22197A30 00000006

OLD3DS (USA)
Luma3DS v9.1
Boot9Strap v1.3
Sharkive v1.0.0

**Comment by JourneyOver** [comment]
Tested all the codes for this game myself and they work just fine even testing now they still work.. O_O

`[Make Timer countdown from 999]` you have to re-activate this every time you enter a new stage or die, it's just the way to code was made.

all the `lower slot` codes require you to pick up two items, and then when you turn on the code you drop whatever is in your lower slot and it'll change to said item from the code.

I'm closing this issue as the codes are not broken.
