### ISSUE TITLE
New codes for super smash bros 3ds

### ISSUE THREAD

**Issue by McShrimp** [BernardoGiordano/Sharkive#74]
[POWER HITS]
00C96E4B 00008049
00C96E4F 00008029
[POWER HEALTH]
00C96E53 00000039
00C96E57 00000049
[DEFLECTION+SHIELD]
00C96E6B 00000045
00C96E6F 00000045
[HIGH+SIDE JUMPS]
00C96E9F 00000041
00C96CD0 3F30303F
[SPEED PL 1]
00C96E60 3FF0F03F
00C96E64 3FF0F03F
[BIG/SMALL PL 1]
00C96CC8 3FE0E03F
00C96CCC 3FE0E03F
[BIG/SMALL CPU 1]
00C9707C 3FE0E03F
00C97080 3FE0E03F
[BIG/SMALL CPU 2]
00C97430 3FE0E03F
00C97434 3FE0E03F
[BIG/SMALL CPU 3]
00C977E4 3FE0E03F
00C977E8 3FE0E03F

**Comment by JourneyOver** [comment]
Doesn't give me any info on TitleID or Region so I don't even know which region this would be for, also please next time do a PR instead of creating an issue for new codes..
