### ISSUE TITLE
Issue with Story of Seasons (US) Codes

### ISSUE THREAD

**Issue by Carejo** [BernardoGiordano/Sharkive#75]
Story of Seasons (US)
CTR-BTSE 0004000000142100

### Working Codes

[Set money to 4 million]

### Partially Working Codes

[Time freezer]
*It resets the current hour to :00 Minutes. The clock continues from there. It doesn't "freeze" it.

[Unlimited Stamina]
*It resets your stamina to full. Your stamina will continue to drain afterwards. It doesn't "freeze" it.

### Not Working Codes

[Infinite Water Alt.]

[Infinite Water]

[Infinite Fertilizer]

[Decrease 1 Hour (L+Y+Down)]

[Increase 1 Hour (L+Y+Up)]

[Decrease 1 Minute (L+Y+Left)]

[Increase 1 Minute (L+Y+Right)]

**Comment by JourneyOver** [comment]
Are you running the latest nightly version of luma? If not please grab it from here https://github.com/Pirater12/luma-nightlies/releases and retest the codes.

**Comment by Carejo** [comment]
Apologies. That fixed it.

**Comment by JourneyOver** [comment]
so by you closing this, I take it that every code you mentioned not working or partially working, is now fully working?

**Comment by Carejo** [comment]
Actually, they don't all work. The Time Manipulation codes, to add or subtract, still don't work.

[Decrease 1 Hour (L+Y+Down)]

[Increase 1 Hour (L+Y+Up)]

[Decrease 1 Minute (L+Y+Left)]

[Increase 1 Minute (L+Y+Right)]

**Comment by JourneyOver** [comment]
Alright, I'll take care of removing those 4 codes later on today as I'm about to head out for a few hours.
