### ISSUE TITLE
Animal Crossing New Leaf (USA) Codes Don't Work

### ISSUE THREAD

**Issue by MagicSheep** [BernardoGiordano/Sharkive#76]
Game: Animal Crossing New Leaf
With Welcome Amiibo Update (Ver. 1.5)
Region: USA
TID: 0004000000086300
CTR-EGDE
Physical and Digital

Working codes:
None of them

Not working:
L+A for unlimited coconut stack
L to copy slot 2 R to paste to slot 1 (turns red)
L+A for 99K bells in slot 1
L+A for golden rose in slot 1
L+A for unlimited Apple Stack
L+A for unlimited Orange Stack
L+A for unlimited Pear Stack
L+A for unlimited Peach Stack
L+A for unlimited Cherry Stack
L+A for unlimited Durian Stack
L+A for unlimited Lemon Stack
L+A for unlimited Lychee Stack
L+A for unlimited Mango Stack
L+A for unlimited Persimmon Stack
L+A for unlimited Banana Stack
L+A for unlimited Bamboo Shoot Stack
L+Right & L+Left to cycle fruit (turns red)
Moon jump (Press L) (turns red)
Unlock Nook's Emporium (turns red)

**Comment by JourneyOver** [comment]
Are you running the latest nightly version of luma? If not please grab it from here Pirater12/luma-nightlies/releases and retest the codes.

**Comment by MagicSheep** [comment]
I retested with the latest Luma nightly and all the codes are not working still. The only change was the "L to copy slot 2 R to paste slot 1" no longer turns red.
