### ISSUE TITLE
Limited number of lines in cheat.txt files. Will it be changed?

### ISSUE THREAD

**Issue by SysmaEngineer** [BernardoGiordano/Sharkive#79]
I've known there's a limit cheat files can be read: In Gateway Mode, cheats files ([ID_number].txt) with more  than 2584 lines can't be read. Also, in Rosalina Menu, cheat.txt files can be read only the first 855 lines. Would you consider the possibility of amplify the cheat.txt file's lines that can be read through Rosalina Menu? I made some large cheat file for one specific game and its number is higher than the Gateway's limit...

**Comment by piepie62** [comment]
That's not an issue with Sharkive, it's an issue with Luma.

**Comment by SysmaEngineer** [comment]
Ups, sorry.

How can I change this thread to another section?

**Comment by piepie62** [comment]
Close this issue, and just open an issue in Luma's repo

**Comment by SysmaEngineer** [comment]
Closed thread.

Reason: wrong repo.
