### ISSUE TITLE
Code Issues with Luigi's Mansion: Dark Moon (US)

### ISSUE THREAD

**Issue by JustPlayJared** [BernardoGiordano/Sharkive#8]
## Issue template

* [] Issue with Sharkive
* [X] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behavior**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**: 00055F00
* **Product code**: CTR-P-AGGE
* **Game version**: 1.0

### Not working codes

* 19,999g (Get 1g for all upgrades)

**Comment by BernardoGiordano** [comment]
Closing because this needs to be re-checked due to latest Luma changes.
