### ISSUE TITLE
Code Issues with Mario Kart 7 (US)

### ISSUE THREAD

**Issue by JustPlayJared** [BernardoGiordano/Sharkive#9]
## Issue template

* [] Issue with Sharkive
* [X] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**: 00030800
* **Product code**: CTR-P-AMKE
* **Game version**: rev0 1.1 and rev0 1.0

### Red codes

- 90000 Coins Collected, Game v1.0
- Mirror Mode Unlocked, Game v1.0
- All Gliders, Game v1.0
- All Wheels, Game v1.0
- All Karts, Game v1.0
- All Characters, Game v1.0
- All Courses, Game v1.0
- Coin x 99,999 v1.0
- 90000 Coins Collected, Rev0 v1.1
- Mirror Mode, Rev0 v1.1
- All Gliders, Rev0 v1.1
- All Wheels, Rev0 v1.1
- All Karts, Rev0 v1.1
- All Courses, Rev0 v1.1
- All Characters, Rev0 v1.1
- Grand Prix Points Modifier
- Coins Modifier
- *Item Cycler Rev0 v1.1
- Water Everywhere, Everytime
- *Moonjump (Hold X)
- *Battle Points Controller
- Infinite Balloons (Battle)
- Gravity modifier
- Region changer
- The Stalking Hack
- (rev0 1.0) VR Modifier (CodyMK7)
- Wins and Losses Modifier rev0 1.1 ONLY
- Auto-Boost
- Total Laps Amount Modifier
- Drunk Driving Code
- Always Draft
- Black Kart
- Instant Respawn
- Disable Bottom Screen
- Force Map Icons
- Disable Blooper Ink
- Disable 1st Person View
- Always First Place
- Hide Item Box Top Screen Icon - REGION
- Instant acceleration rev1
- Instant acceleration rev0
- Instant backwards acceleration rev1
- Instant backwards acceleration rev0
- Instant stop rev1
- Instant stop rev0
- *Press START + L + R to respawn - rev0
- *Press START + L + R to respawn - rev1
- No first person view - rev0
- Bill Ball Controller
- Status invincible - rev0
- Stalking Hack 2.0 (X)

White codes confirmed not working

- Gyro Controls Without First Person Came
- 4:59.99xx Timer
- Allow Front-face Clipping
- Can always drift
- Position Modifier
- Totally disable first person view - rev

White codes confirmed working

- *Press L+R+Start to respawn ASM - USA Re (second slot, last page)

**Comment by BernardoGiordano** [comment]
Codes with v1.0 should be checked for the v1.0 of the game too, for being entirely sure

**Comment by JustPlayJared** [comment]
All the codes that I've posted so far are just the ones that pop up in red. I'm going to go back through them to find the white codes that don't work later.

**Comment by Slattz** [comment]
A special case is MK7 (& I think SM3D Land) where there is also different revisions. So you may be using a rev 1 game which is why rev 0 codes don't work.
For MK7, rev 1 is the base game with the v1.1 update built-in. Whereas rev0 is just the game, no update built-in, you have to download the update yourself.
rev 0 v1.1 also has different offsets to rev 1 btw.

**Comment by JustPlayJared** [comment]
@Slattz I'm using rev0, then. I'll edit the post to show that.

**Comment by BernardoGiordano** [comment]
Closing because this needs to be re-checked due to latest Luma changes.
